### PR TITLE
Use PDL::LinearAlgebra instead of bundled Fortran code

### PR DESCRIPTION
**Pull request by mohawk2**
LAPACK's `cgtsv`'s subdiagonal argument doesn't start from the second element, unlike LINPACK's one. I used the `mv`/`rotate` etc trick that you used for the superdiagonal (where that was otherwise the same data as the subdiagonal) to make it line up right, but you should now be able to drop the whole "dummy zero" concept, and remove the rotates as well.

I've converted the build to use ExtUtils::MakeMaker because I was getting errors from the Module::Build without the pluggable stuff.

Also it looks like there are no tests for the `LE::NR2::SH*` modules, so I was flying a bit blind there in converting them? It would be useful to add tests for those.

### CODE REVIEW

**Comment by wlmb** [comment]
@mohawk2 mohawk
I checked your version and it seems to work. I don't have tests for the SH code as I don't have simple systems for which I have analytical results to compare to. There are some checks though that could be done, such as checking the symmetry of the resulting tensors. I'll think about it.

If I remember correctly, I guess I chose Build.PL over Makefile.PL in order to build automatically the library for the fortran routines. I I need that in the future, I guess it could be managed with Makefile.PL, (somehow, PDL does that), right? The other advantage I recall reading is that it is pure Perl code, but maybe that is not too relevant. I believe Makefile.PL is much more popular. What are the relevant advantages/disadvantages between the two systems?

Thanks again for all the work.

**Comment by mohawk2** [comment]
You're most welcome!

Yes, with EUMM (which drives Makefile.PL) you can still automate building Fortran libraries, exactly as you say - PDL does this in its "big PDL" version with (among others) the SLATEC routines (although those will all be getting cut out into their own distributions soon). In general, I'd suggest the first place to start with using Fortran would be other PDL libraries that already do that (such as PDL::LinearAlgebra), in order to separate maintaining underlying libraries from the applications that use them. If an existing library doesn't provide the Fortran routines you wanted, then either an existing one could be made to do so, or else it would be a good idea to make one, then use it within the application. A good starting point in considering that would be to email the PDL lists to get others' ideas!

The pros and cons of MB vs EUMM are discussed in the Module::Build documentation. These days the recommendation is to use EUMM. Separately, and as mentioned above, I'd recommend this exact project stay as this PR makes it, a pure-Perl one, and have any Fortran (or even other PP routines) live in a different distribution. It's conceivable that might change if Photonic were to show some routines that really should be written in PP, and that are incredibly specific to the physics application here, but it does seem a bit unlikely :-)

**Comment by wlmb** [comment]
Thanks!

**Comment by mohawk2** [comment]
Very welcome! How about a new CPAN release? :-)

**Comment by wlmb** [comment]
Yes, why not. Done. I have been busy so I did it in a hurry. I hope with not too many mistakes. V 0.015

**Comment by mohawk2** [comment]
Seems to work great!

**Comment by wlmb** [comment]
Good!
I get a series of errors from the github actions. Do you know how can I obtain more details about the failures (what in the code caused them).
Regards,

**Comment by mohawk2** [comment]
If you look at the list of commits (such as https://github.com/wlmb/Photonic/commits/master), you should see CI results by each one: a tick, cross, or circle if still running. Clicking the icon drops down a box showing results/progress. Clicking each one views that result. There are often useful error messages on those.

For reasons I haven't fully investigated, the code-coverage results are a bit volatile, and a drop in coverage, however small, triggers a "failure". It's important to look at the results for a commit, and see whether the only failure is for coverage.

**Comment by wlmb** [comment]
Thanks! I meant errors as the following:

    Error: Prototype mismatch: sub PDL::(-: none vs (;@) at /opt/hostedtoolcache/perl/5.30.3/x64/lib/5.30.3/overload.pm line 48.

I'm not sure if it is an error in PDL or an error triggered by my code, but, what was my code doing? which line of which file in my code was executing?

Regards

**Comment by mohawk2** [comment]
This is a compile-time issue, and isn't entirely an error. Is it only on Perl 5.30? Probably the PP code needs to generate the Perl-sub with the right prototype. It might need an additional key/value for `pp_def`. If you can cut this down to which Perl version need this, and which test files trigger it if it's only some, I can fix it :-) When you have that info, could you open an issue on the PDL repo?

As a cut-down version of that process, it would be helpful if you at least paste the URL with the specific line of the "actions" run that I'd be able to look at. If it's not from CI, then the info specified above.

**Comment by wlmb** [comment]
Yes, it does pass the tests. I only saw that in 5.30. Not in 5.20 and not in 5.14. I don't see those messages when I test in my laptop, but they appeared in the github actions report.  For example, in  https://github.com/wlmb/Photonic/runs/2043717206?check_suite_focus=true in  'run release tests' around line 92 of the report.

**Comment by mohawk2** [comment]
I see that the PDL that was giving those errors was 2.026, which is a little out of date. #11 adds a test to show what version of all given prereqs is installed, which is handy when debugging both CI runs, and CPAN Testers reports. I'd suggest that since the only thing that's giving an error is the two pod-coverage author tests, there isn't an actual problem?

**Pull request merged**
