### PR TITLE
Tweaks towards native complex still

### PR DESCRIPTION
**Pull request by mohawk2**

### CODE REVIEW

**Comment by wlmb** [comment]
At some time the name of apply_operator you factored and moved into Utils.pm ought to change. I realized after the first few versions of the package that the Haydock technique could be applied to any operator, not only the operators I was using to homegenize the dielectric function. Thus, I allowed the modules to supply their own 'operator' as a method applyOperator. You factored out two of these: one of these takes the longitudinal projection of the characteristic function B and the other takes the longitudinal projection of the dielectric function epsilon. But the concept of supplying an applyOperator method might go beyond those two. Thus I guess apply_longitudinal_projection might be a better name for the new routine in Utils.

**Comment by mohawk2** [comment]
I'm very pleased to rename any of the util functions - please just say to what :-)

**Comment by mohawk2** [comment]
First I need to fix the currently-broken commit :-)

**Comment by wlmb** [comment]
On the other hand, I'm curious about i vs i() vs ci vi ci(). I recall from a recent discussion that ci requires the parenthesis to avoid potential misinterpretations, as it is a function. How come i doesn't have the same problem? I guess there is a prototype for i() somewhere. Could the same be done for ci? It is not important, but I guess i looks nicer than i().

**Comment by mohawk2** [comment]
> On the other hand, I'm curious about i vs i() vs ci vi ci(). I recall from a recent discussion that ci requires the parenthesis to avoid potential misinterpretations, as it is a function. How come i doesn't have the same problem? I guess there is a prototype for i() somewhere. Could the same be done for ci? It is not important, but I guess i looks nicer than i().

`i` in PDL::Complex is a constant, not a function, so Perl can't misinterpret it. `ci` was a function (it's now gone in PDL 2.047). Main PDL, not just PDL::Complex, now (as of today) has an `i()` function that works like `inf()` - you can give it dimensions, or an ndarray to get dimensions from, and it will create an ndarray with the square root of -1 as all its values. I've been going through and changing (as you'll have seen) some of the uses of `i` to different idioms, such as `i2C` or `czip`.

**Comment by mohawk2** [comment]
> Thus I guess apply_longitudinal_projection might be a better name for the new routine in Utils.

Renamed!

**Comment by wlmb** [comment]
> `i` in PDL::Complex is a constant, not a function, so Perl can't misinterpret it. `ci` was a function (it's now gone in PDL 2.047).

Things are moving fast :) I hadn't realized it.

> Main PDL, not just PDL::Complex, now (as of today) has an `i()` function that works like `inf()` - you can give it dimensions

Ok. Now I get it.

> or an ndarray to get dimensions from, and it will create an ndarray with the square root of -1 as all its values. I've been going through and changing (as you'll have seen) some of the uses of `i` to different idioms, such as `i2C` or `czip`.

Sorry, what is czip?

**Comment by wlmb** [comment]
> > Thus I guess apply_longitudinal_projection might be a better name for the new routine in Utils.
> 
> Renamed!

You're fast!!

**Comment by mohawk2** [comment]
> > or an ndarray to get dimensions from, and it will create an ndarray with the square root of -1 as all its values. I've been going through and changing (as you'll have seen) some of the uses of `i` to different idioms, such as `i2C` or `czip`.
>
> Sorry, what is czip?

A new function that takes two values (ndarrays, or just Perl values) and returns a native-complex with the first one as the real part and the second one the imaginary part.

**Comment by wlmb** [comment]
> > Sorry, what is czip?
> 
> A new function that takes two values (ndarrays, or just Perl values) and returns a native-complex with the first one as the real part and the second one the imaginary part.

Great!

**Comment by mohawk2** [comment]
> One other thing. I saw that you converted B to complex B->r2C when calling apply_operator from modified Photonic::LE::NR2::OneH. It would be unnecessary as reals and complexes can interoperate. But on the other hand, you need $coeff to be a PDL::Complex, as you add a dummy dimension at position 1 to allow for the real and imaginary index at position 0. What is the advantage of adding a dummy dimension to $coeff instead of moving the cartesian index to the end? One advantage, I guess, of not converting B to complex is that multiplication of complex*real involves only to real multiplications, while multiplication of complex times complex requires four multiplications and two additions, so it is slower, right?

That change was largely to simplify the function, so that adding dummy dims could be done in a consistent way rather than detecting where to insert the dummy dimension. Multiplying complex numbers may well be slightly slower than complex * real, but without using the PDL::Complex `Cscale` function there isn't really a clear, idiomatic way to achieve that with native complex. I feel that trying to do so is a form of premature optimisation, when clarity is far more valuable. This is your codebase, so you decide, but that's my opinion :-)

**Comment by mohawk2** [comment]
By the way, how important is it to keep `linearCombineIt` with iterators? By turning all the `nextval` stuff into ndarrays, that would allow a lot of vectorisation, which would both remove `for` loops, shorten and simplify code, and almost certainly run faster too as you'd stay in C land more, and spend less time in Perl land.

**Comment by wlmb** [comment]
> > One other thing. I saw that you converted B to complex B->r2C when calling apply_operator from modified Photonic::LE::NR2::OneH. It would be unnecessary as reals and complexes can interoperate. But on the other hand, you need $coeff to be a PDL::Complex, as you add a dummy dimension at position 1 to allow for the real and imaginary index at position 0. What is the advantage of adding a dummy dimension to $coeff instead of moving the cartesian index to the end? One advantage, I guess, of not converting B to complex is that multiplication of complex*real involves only to real multiplications, while multiplication of complex times complex requires four multiplications and two additions, so it is slower, right?
> 
> That change was largely to simplify the function, so that adding dummy dims could be done in a consistent way rather than detecting where to insert the dummy dimension. Multiplying complex numbers may well be slightly slower than complex * real, but without using the PDL::Complex `Cscale` function there isn't really a clear, idiomatic way to achieve that with native complex. I feel that trying to do so is a form of premature optimisation, when clarity is far more valuable. This is your codebase, so you decide, but that's my opinion :-)

Well, I guess that with native complexes the dummy index would go into position 0 irrespective of having real or complex $coeff's, so maybe changing back to real B's could be done later. A comment near r2C may help in the future.

**Comment by wlmb** [comment]
> By the way, how important is it to keep `linearCombineIt` with iterators? By turning all the `nextval` stuff into ndarrays, that would allow a lot of vectorisation, which would both remove `for` loops, shorten and simplify code, and almost certainly run faster too as you'd stay in C land more, and spend less time in Perl land.

The problem is that the states take a lot of space, and one may need many states, so it may be necessary to send them out to disk. What's nice of the iterator is that the rest of the code doesn't care if the states are in a file or in memory. When they are in memory it would be faster to use ndarrays, but my guess is that the difference is not so large, as each iteration may do thousands or millions of operations (adding a number times a state, each of which might be a large ndarray).

**Comment by mohawk2** [comment]
> > By the way, how important is it to keep `linearCombineIt` with iterators? By turning all the `nextval` stuff into ndarrays, that would allow a lot of vectorisation, which would both remove `for` loops, shorten and simplify code, and almost certainly run faster too as you'd stay in C land more, and spend less time in Perl land.
> 
> The problem is that the states take a lot of space, and one may need many states, so it may be necessary to send them out to disk. What's nice of the iterator is that the rest of the code doesn't care if the states are in a file or in memory. When they are in memory it would be faster to use ndarrays, but my guess is that the difference is not so large, as each iteration may do thousands or millions of operations (adding a number times a state, each of which might be a large ndarray).

For doing things with ndarrays, we shouldn't forget the value of clarity for maintenance. However! For handling very large data that you don't want in memory, there is also PDL::IO::FastRaw, specifically its `mapfraw` function. I now understand the motivation for the for-loop to accumulate results without trying to load everything in memory (which I suspected, but wanted to confirm :-).

I will in due course look at changing Photonic::Roles::AllH from its current bespoke approach to using PDL::IO::FastRaw. Assuming that works, would you agree it would then make sense to switch to "all the states" being a single ndarray, albeit maybe on disk using this?

**Comment by mohawk2** [comment]
> Well, I guess that with native complexes the dummy index would go into position 0 irrespective of having real or complex $coeff's, so maybe changing back to real B's could be done later. A comment near r2C may help in the future.

My thinking here is that aside from the legacy `Cscale` thing (which would be quite complicated to implement for native complex), any multiplication would involve silently upgrading the real `B` to complex, which would have a cost when done repeatedly. I think a better way would be to require `B` to be complex from the start, just to avoid that cost. This would involve just adding the type constraint to the `has` declaration. What do you think?

**Comment by wlmb** [comment]
> > > By the way, how important is it to keep `linearCombineIt` with iterators? By turning all the `nextval` stuff into ndarrays, that would allow a lot of vectorisation, which would both remove `for` loops, shorten and simplify code, and almost certainly run faster too as you'd stay in C land more, and spend less time in Perl land.
> > 
> > 
> > The problem is that the states take a lot of space, and one may need many states, so it may be necessary to send them out to disk. What's nice of the iterator is that the rest of the code doesn't care if the states are in a file or in memory. When they are in memory it would be faster to use ndarrays, but my guess is that the difference is not so large, as each iteration may do thousands or millions of operations (adding a number times a state, each of which might be a large ndarray).
> 
> For doing things with ndarrays, we shouldn't forget the value of clarity for maintenance. However! For handling very large data that you don't want in memory, there is also PDL::IO::FastRaw, specifically its `mapfraw` function. I now understand the motivation for the for-loop to accumulate results without trying to load everything in memory (which I suspected, but wanted to confirm :-).
> 
> I will in due course look at changing Photonic::Roles::AllH from its current bespoke approach to using PDL::IO::FastRaw. Assuming that works, would you agree it would then make sense to switch to "all the states" being a single ndarray, albeit maybe on disk using this?

I experimented in 2018 with PDL::IO::FastRaw but I didn't write down and don't remember why I didn't use it finally. I couldn't use it interactively with the pdl script. I considered mapflex but didn't consider mapfraw, I don't know why. Now I'm not sure where did I found mapflex, as it is not part (now) of FastRaw. Looking now at the documentation it seems mapfraw should provide a nice solution to keeping states without filling the ram.

**Comment by wlmb** [comment]
> > Well, I guess that with native complexes the dummy index would go into position 0 irrespective of having real or complex $coeff's, so maybe changing back to real B's could be done later. A comment near r2C may help in the future.
> 
> My thinking here is that aside from the legacy `Cscale` thing (which would be quite complicated to implement for native complex), any multiplication would involve silently upgrading the real `B` to complex, which would have a cost when done repeatedly. I think a better way would be to require `B` to be complex from the start, just to avoid that cost. This would involve just adding the type constraint to the `has` declaration. What do you think?

I didn't expect real*complex to promote the real to complex first, as complex*complex is about 3 times more expensive. Is this promotion a PDL or a native C thing? If it is a PDL decision, could it be fixed in some future? (I understand that complexity increases if you start allowing operations between different types). I'm somehow reluctant to slow down what I guess is the most expensive part of the calculation (repetitively applying the operator), but maybe it is acceptable to simplify the code during the transition to native complex.

I wouldn't like to require B to be complex through a type constraint, as that would break the existing codes. Maybe a better solution would be to add a new lazy complexified B field initialized with B->r2C upon its first use.

**Comment by mohawk2** [comment]
> > I will in due course look at changing Photonic::Roles::AllH from its current bespoke approach to using PDL::IO::FastRaw. Assuming that works, would you agree it would then make sense to switch to "all the states" being a single ndarray, albeit maybe on disk using this?
> 
> I experimented in 2018 with PDL::IO::FastRaw but I didn't write down and don't remember why I didn't use it finally. I couldn't use it interactively with the pdl script. I considered mapflex but didn't consider mapfraw, I don't know why. Now I'm not sure where did I found mapflex, as it is not part (now) of FastRaw. Looking now at the documentation it seems mapfraw should provide a nice solution to keeping states without filling the ram.

`mapflex` is part of https://metacpan.org/pod/PDL::IO::FlexRaw, which is intended to read and write Fortran files. Since that's not a requirement here, it seems to me that FastRaw is a better fit. Both libraries have been in PDL since the early '00s, but since there's so much stuff in there, it can be nearly impossible to know what's actually available!

Am I right that you would be happy with `as` and `bs` (etc) also being ndarrays, rather than array-refs as now? I'd like to see everything where it's practicable to switch to being more vectorised.

**Comment by mohawk2** [comment]
> > > Well, I guess that with native complexes the dummy index would go into position 0 irrespective of having real or complex $coeff's, so maybe changing back to real B's could be done later. A comment near r2C may help in the future.
> > 
> > 
> > My thinking here is that aside from the legacy `Cscale` thing (which would be quite complicated to implement for native complex), any multiplication would involve silently upgrading the real `B` to complex, which would have a cost when done repeatedly. I think a better way would be to require `B` to be complex from the start, just to avoid that cost. This would involve just adding the type constraint to the `has` declaration. What do you think?
> 
> I didn't expect `real * complex` to promote the real to complex first, as `complex * complex` is about 3 times more expensive. Is this promotion a PDL or a native C thing? If it is a PDL decision, could it be fixed in some future? (I understand that complexity increases if you start allowing operations between different types). I'm somehow reluctant to slow down what I guess is the most expensive part of the calculation (repetitively applying the operator), but maybe it is acceptable to simplify the code during the transition to native complex.

That's a great question, and one to look into. Maybe PDL main does need a `scale` to match `Cscale`. Let's leave this unmerged for now, until I've investigated that - with the `real` type qualifier, it should actually not be very difficult (though not entirely trivial).

> I wouldn't like to require B to be complex through a type constraint, as that would break the existing codes. Maybe a better solution would be to add a new lazy complexified B field initialized with B->r2C upon its first use.

I think it's most likely we'll be able to retain a "scale" capability, so this won't be an issue. However, just for your awareness, this sort of thing is achievable in Moo\* without breaking existing code through the use of type coercions, here from a `PDL` to a `PDLComplex` via a simple call to `r2C`.

**Comment by mohawk2** [comment]
Here are the docs: https://metacpan.org/pod/distribution/Moose/lib/Moose/Manual/Types.pod#COERCION

**Comment by wlmb** [comment]
> Am I right that you would be happy with `as` and `bs` (etc) also being ndarrays, rather than array-refs as now? I'd like to see everything where it's practicable to switch to being more vectorised.

Yes, though I have a question. I did consider making as, bs ndarrays, but as I did accessed them sequentially I had the doubt: is using a Slice to get at one element '$ndarray-slice("(($n))")' or NiceSlice's '$ndarray(($nfaster))' or slower than using a perl array element access '$array[$n]' or '$arrayref->[$n]'?

**Comment by wlmb** [comment]
> I think it's most likely we'll be able to retain a "scale" capability, so this won't be an issue. However, just for your awareness, this sort of thing is achievable in Moo* without breaking existing code through the use of type coercions, here from a `PDL` to a `PDLComplex` via a simple call to `r2C`.

Thanks for the tip!

**Comment by mohawk2** [comment]
> > Am I right that you would be happy with `as` and `bs` (etc) also being ndarrays, rather than array-refs as now? I'd like to see everything where it's practicable to switch to being more vectorised.
> 
> Yes, though I have a question. I did consider making as, bs ndarrays, but as I did accessed them sequentially I had the doubt: is using a Slice to get at one element '$ndarray-slice("(($n))")' or NiceSlice's '$ndarray(($nfaster))' or slower than using a perl array element access '$array[$n]' or '$arrayref->[$n]'?

I haven't run a benchmark, though it probably wouldn't be hard to do so. It seems unlikely that it would make a big difference. What *would* make a difference is that if everything is an ndarray (maybe including some that are mem-mapped), then they can just all be processed with single PDL operations, which would maximise performance, including allowing for using PDL pthreads for multi-core processing.

**Comment by wlmb** [comment]
> I haven't run a benchmark, though it probably wouldn't be hard to do so. It seems unlikely that it would make a big difference. What _would_ make a difference is that if everything is an ndarray (maybe including some that are mem-mapped), then they can just all be processed with single PDL operations, which would maximise performance, including allowing for using PDL pthreads for multi-core processing.

Sounds good...

**Comment by mohawk2** [comment]
Speaking of benchmarks, are any of the `examples` usable as performance-measuring programs? Also, could you share (either on here, or by pushing it to the repo) your experiments for the `tensor` function so I can be sure any changes I make to it are actually correct?

**Comment by wlmb** [comment]
> Speaking of benchmarks, are any of the `examples` usable as performance-measuring programs? Also, could you share (either on here, or by pushing it to the repo) your experiments for the `tensor` function so I can be sure any changes I make to it are actually correct?

I made t/tensor.t to test the tensor function in Utils. I did find what I believe is a mistake. When making slices to build the tensor I had to protect the index '($n)' instead of '$n', so that the resulting dimensions don't get an erroneous size 1.

I also believe that the $after_cb routine is acting too early, as it changes the size of dimension 1, so that the iteration over $i and $j produced values of the index $n that were out of range. This routine was employed in SHChiTensor, so my guess is that currently SHChiTensor is broken. The test passed, but it is a 1D test only. The number of dimensions and the number of pairs of basis vectors coincide only in 1D.

I uploaded to my master branch the new Util and the new test. 

About the examples, I'll upload a recent simple 3D example.

**Comment by wlmb** [comment]
> I will in due course look at changing Photonic::Roles::AllH from its current bespoke approach to using PDL::IO::FastRaw. Assuming that works, would you agree it would then make sense to switch to "all the states" being a single ndarray, albeit maybe on disk using this?

By the way, I started playing with mapfraw.   I found that the time changes dramatically with loop organization

` my $x=mapfraw("rem.dat", {Creat=>1, Dims=>[$N,1000,1000], Datatype=>cdouble});
 for(0..$N-1){
     $x(($_)).=$_*sequence(1000,1000);
 }
`
With $N=300 the program above takes forever. I was dissapointed, but the realized that if I move $N to the last dimension it takes about 17 secs. for $N=300. However, if I remove the loop and write instead
`$x=sequence($N)->(*1,*1)*sequence(1000,1000);`
the time goes down to a couple of seconds.

Do you know how does mapfraw decides how much of the data structure to keep in ram?

**Comment by wlmb** [comment]
> Speaking of benchmarks, are any of the `examples` usable as performance-measuring programs? 
I added a 3D example that computes the response of a lattice of tori. The usage example in the initial comments takes almost 4mins. in my laptop, so I think it is long enough to be used for performance testing of the LE/NR2 routines. It is not a systematic benchmark though.

**Comment by mohawk2** [comment]
> > I will in due course look at changing Photonic::Roles::AllH from its current bespoke approach to using PDL::IO::FastRaw. Assuming that works, would you agree it would then make sense to switch to "all the states" being a single ndarray, albeit maybe on disk using this?
> 
> By the way, I started playing with mapfraw. I found that the time changes dramatically with loop organization
> 
> `my $x=mapfraw("rem.dat", {Creat=>1, Dims=>[$N,1000,1000], Datatype=>cdouble}); for(0..$N-1){ $x(($_)).=$_*sequence(1000,1000); }`
> With $N=300 the program above takes forever. I was dissapointed, but the realized that if I move $N to the last dimension it takes about 17 secs. for $N=300. However, if I remove the loop and write instead
> `$x=sequence($N)->(*1,*1)*sequence(1000,1000);`
> the time goes down to a couple of seconds.

This isn't surprising, and is a consequence of how often one transitions between "Perl land" and "PDL land". I believe it's a universal mistake to use `for` loops in PDL where there is any alternative at all.

Rather than the slice notation, wouldn't the above be better with just `sequence(1, 1, $N)`? (yes, I had to check it gives the same result! But it does)

> Do you know how does mapfraw decides how much of the data structure to keep in ram?

I'm afraid I don't, but I suspect it's the OS in charge, and I would expect it to work well.

**Comment by wlmb** [comment]
> > `$x=sequence($N)->(*1,*1)*sequence(1000,1000);`
> > the time goes down to a couple of seconds.
> 
> This isn't surprising, and is a consequence of how often one transitions between "Perl land" and "PDL land". I believe it's a universal mistake to use `for` loops in PDL where there is any alternative at all.
> 
> Rather than the slice notation, wouldn't the above be better with just `sequence(1, 1, $N)`? (yes, I had to check it gives the same result! But it does)

Yes, of course.

> > Do you know how does mapfraw decides how much of the data structure to keep in ram?
> 
> I'm afraid I don't, but I suspect it's the OS in charge, and I would expect it to work well.

Ok. I was wondering if it would adapt the amount of ram according to the presence of other ram-demanding programs. If the OS is in charge, then I guess I would adapt.

**Comment by mohawk2** [comment]
> > Speaking of benchmarks, are any of the `examples` usable as performance-measuring programs?
> 
> I added a 3D example that computes the response of a lattice of tori. The usage example in the initial comments takes almost 4mins. in my laptop, so I think it is long enough to be used for performance testing of the LE/NR2 routines. It is not a systematic benchmark though. It is at examples/LE/NR2/toroid.pl

That does sound like an excellent benchmark. Have you tried using the `set_autopthread_targ` functionality to get it to use all the cores?

**Comment by wlmb** [comment]
> > > Speaking of benchmarks, are any of the `examples` usable as performance-measuring programs?
> > 
> > 
> > I added a 3D example that computes the response of a lattice of tori. The usage example in the initial comments takes almost 4mins. in my laptop, so I think it is long enough to be used for performance testing of the LE/NR2 routines. It is not a systematic benchmark though. It is at examples/LE/NR2/toroid.pl
> 
> That does sound like an excellent benchmark. Have you tried using the `set_autopthread_targ` functionality to get it to use all the cores?
I hadn't, but I'm trying it now. I didn't use  
4 cores: real    2m52.199s, user    4m19.320s,  sys     0m53.196s
3 cores: real    2m53.965s, user    4m24.333s,  sys     0m53.394s
2 cores: real    4m2.130s,   user    3m34.809s,  sys     0m55.675s
1 core:   real    3m52.869s, user    3m18.241s,  sys     0m34.446s
Somewhat surprising. I didn't set_autopthread_size though.

**Comment by mohawk2** [comment]
> > That does sound like an excellent benchmark. Have you tried using the `set_autopthread_targ` functionality to get it to use all the cores?
>
> I hadn't, but I'm trying it now. I didn't use
> `4 cores: real    2m52.199s, user    4m19.320s,  sys     0m53.196s`
> `3 cores: real    2m53.965s, user    4m24.333s,  sys     0m53.394s`
> `2 cores: real    4m2.130s,   user    3m34.809s,  sys     0m55.675s`
> `1 core:   real    3m52.869s, user    3m18.241s,  sys     0m34.446s`
> Somewhat surprising. I didn't set_autopthread_size though.

Something that may be relevant: the number of threads needs to divide exactly into (I think) the highest dimension, in order to work right. That seems like it should be fixed, but I haven't got to it yet :-)

**Comment by wlmb** [comment]
> 
> Something that may be relevant: the number of threads needs to divide exactly into (I think) the highest dimension, in order to work right. That seems like it should be fixed, but I haven't got to it yet :-)

I understand it is not the highest, but any of threaded dimensions. Anyway, until changed, one has to be aware of this limitation to maximize the full advantage of parallelization.

**Comment by wlmb** [comment]
> > I didn't expect `real * complex` to promote the real to complex first, as `complex * complex` is about 3 times more expensive. Is this promotion a PDL or a native C thing? If it is a PDL decision, could it be fixed in some future? (I understand that complexity increases if you start allowing operations between different types). I'm somehow reluctant to slow down what I guess is the most expensive part of the calculation (repetitively applying the operator), but maybe it is acceptable to simplify the code during the transition to native complex.
> 
> That's a great question, and one to look into. Maybe PDL main does need a `scale` to match `Cscale`. Let's leave this unmerged for now, until I've investigated that - with the `real` type qualifier, it should actually not be very difficult (though not entirely trivial).
> 
Just checked timing with variations on a one-liner:
 `time perl -MPDL -MPDL::Complex -E '$PDL::BIGPDL=1; $a=sequence(10000,10000)->r2C; $b=sequence(10000,10000); say +($a*$b)->sum'`
To my surprise, complex*real takes longer than Cscale(complex,real) which takes longer than complex*complex. So I guess that promoting a real ndarray to complex isn't something to worry about.

**Comment by mohawk2** [comment]
> > Something that may be relevant: the number of threads needs to divide exactly into (I think) the highest dimension, in order to work right. That seems like it should be fixed, but I haven't got to it yet :-)
> 
> I understand it is not the highest, but any of threaded dimensions. Anyway, until changed, one has to be aware of this limitation to maximize the full advantage of parallelization.

Quite right! https://metacpan.org/pod/PDL::ParallelCPU#How-It-Works

**Comment by mohawk2** [comment]
> Just checked timing with variations on a one-liner:
> `time perl -MPDL -MPDL::Complex -E '$PDL::BIGPDL=1; $a=sequence(10000,10000)->r2C; $b=sequence(10000,10000); say +($a*$b)->sum'`
> To my surprise, `complex*real` takes longer than `Cscale(complex,real)` which takes longer than `complex*complex`. So I guess that promoting a real ndarray to complex isn't something to worry about.

Can I confirm you've also checked the results are correct? I quickly checked `complex.pd`, and it looks like `Cmul` may well be threading over the "real" if given, which would give the right results only if it didn't inconveniently have a first dim of 2. The PDL::Complex thing really is a minefield!

**Comment by wlmb** [comment]
> Can I confirm you've also checked the results are correct? I quickly checked `complex.pd`, and it looks like `Cmul` may well be threading over the "real" if given, which would give the right results only if it didn't inconveniently have a first dim of 2. The PDL::Complex thing really is a minefield!

Well, I obtained 3.33333e23 in all cases, which agrees with the leading term of the exact result n^3/3, with n=1e8. 

I agree; PDL::Complex is a headache. Cscale assumes the left side is a dim2 PDL or PDL::Complex and the right hand side is a real scalar. If by mistake you permute them, the left side is replicated to become of dim2 and it there is threading over the right side. Thus
`
pdl> p Cscale(pdl(2,3)->complex, 5)
10 +15i # correct
pdl> p Cscale(5, pdl(2,3)->complex)

[                   # the 5 is interpreted as pdl(5,5) 
 [10 10]  
 [15 15]
]
`

Cmul expects the two arguments to be of dimension 2, thus it cannot be used to multiply by a real scalar:
`
pdl> p Cmul(pdl(2,3)->complex, pdl(5,7))                                   
-11 +29i # correct
pdl> p Cmul(pdl(2,3), pdl(5,7)->complex)
[-11 29] # correct but not PDL::Complex
pdl> p Cmul(pdl(2,3)->complex, 5) 
-5 +25i # the 5 is interpreted as pdl(5,5)
`
Thus it seems the problem is not having dimension==2, but having dimension!=2

**Comment by mohawk2** [comment]
Yeah, PDL::Complex does what it does Ok, but it is very incomplete. Fixing it would end us up with the same as native complex, which would break your code in an identical fashion. Let's leave that as it is, which presently works for you, and I'll carry on this migration. Current state of play: I'm at a point where due to wrong (for native) slicing, it's causing segfaults in PDL::LinearAlgebra. That shouldn't be possible, so that's a bug I'll fix.

Meanwhile, is this PR in an acceptable state to merge as an incremental change? If you need me to redo it without the `->r2C` change as discussed, I'll be happy to.

**Comment by wlmb** [comment]
> Current state of play: I'm at a point where due to wrong (for native) slicing, it's causing segfaults in PDL::LinearAlgebra. That shouldn't be possible, so that's a bug I'll fix.

Yeah. For the course I'm teaching I made a program using (for the first time) native complex. It is very nice not having to keep track of the first index. I tried to imitate you lu routines in terms of the PDL::LinearAlgebra, and I got segfaults.  So I went back to my old code, separating the real and imaginary parts and using the real lu routines. 

By the way, I understand that for   PDL::LinearAlgebra::Real and PDL::LinearAlgebra::Complex the first index of a matrix denotes rows and the second columns, while PDL::LinearAlgebra (without the third component) uses the PDL convention, for which the first index is the column and the second the row. Did you take account of this in your lu routines? It shouldn't be of importance for symmetric matrices, but sometimes non-symmetric matrices appear, so the convention being used should be clear for the user.

> Meanwhile, is this PR in an acceptable state to merge as an incremental change? 

Done.

> If you need me to redo it without the `->r2C` change as discussed, I'll be happy to.

I believe that the r2C change is not a problem, as I found complex-complex operations are currently faster than real-complex. As you suggested, it may even be coerced (in the future, when we use native complex's, so that B doesn't get an additional dimension elsewhere).

What still worries me somewhat is the  $after_cb parameter of the tensor sub in Photonic::Utils. I haven't understood it but I suspect it is wrong and that if it worked in the SHG tests, it is because they are currently in 1D, but would fail in more dimensions.

**Comment by wlmb** [comment]
On the other hand, a colleague tried to upgrade his Photonic installation, so he had to upgrade his PDL::LinearAgebra installation. Installation failed on version 0.018. It seems it is related to ci() disappearing. i() has different meanings if PDL::Complex is or is not loaded, so I guess this would have to be documented. I saw that you already modified the failing test in the github repository.

**Comment by mohawk2** [comment]
> On the other hand, a colleague tried to upgrade his Photonic installation, so he had to upgrade his PDL::LinearAgebra installation. Installation failed on version 0.018. It seems it is related to ci() disappearing. i() has different meanings if PDL::Complex is or is not loaded, so I guess this would have to be documented. I saw that you already modified the failing test in the github repository.

Not long after you wrote this, I released PDL::LinearAlgebra 0.19 which fixes this. Sorry to have not seen this till just now. Could you ask your colleague to try again?

**Comment by mohawk2** [comment]
> > Current state of play: I'm at a point where due to wrong (for native) slicing, it's causing segfaults in PDL::LinearAlgebra. That shouldn't be possible, so that's a bug I'll fix.
> 
> Yeah. For the course I'm teaching I made a program using (for the first time) native complex. It is very nice not having to keep track of the first index. I tried to imitate you lu routines in terms of the PDL::LinearAlgebra, and I got segfaults. So I went back to my old code, separating the real and imaginary parts and using the real lu routines.

Could you post some sample code that triggers this? I probably already have a good test case but it doesn't do any harm to make sure your specific example will work with the fixed code.

> By the way, I understand that for PDL::LinearAlgebra::Real and PDL::LinearAlgebra::Complex the first index of a matrix denotes rows and the second columns, while PDL::LinearAlgebra (without the third component) uses the PDL convention, for which the first index is the column and the second the row. Did you take account of this in your lu routines? It shouldn't be of importance for symmetric matrices, but sometimes non-symmetric matrices appear, so the convention being used should be clear for the user.

I haven't changed anything about the code for native-complex - the underlying Fortran routines are exactly the same. I currently suspect the problem is from the `RedoDims` code, but haven't dug into it yet.

> > Meanwhile, is this PR in an acceptable state to merge as an incremental change?
> 
> Done.

Thanks!

> What still worries me somewhat is the $after_cb parameter of the tensor sub in Photonic::Utils. I haven't understood it but I suspect it is wrong and that if it worked in the SHG tests, it is because they are currently in 1D, but would fail in more dimensions.

I added the callback parameter that was intended to behave identically to the code that it was replacing in the other similar `tensor`-like (but with an extra dimension) code. If you tell me some code I have made for this stuff has a bug, I of course believe you! Can you make a test-case that captures the error?

**Comment by wlmb** [comment]
> > On the other hand, a colleague tried to upgrade his...
> 
> Not long after you wrote this, I released PDL::LinearAlgebra 0.19 which fixes this. Sorry to have not seen this till just now. Could you ask your colleague to try again?

I just asked him. Will tell you afterwards.

**Comment by wlmb** [comment]
> > Yeah. For the course I'm teaching I made a program using (for the first time) native complex. It is very nice not having to keep track of the first index. I tried to imitate you lu routines in terms of the PDL::LinearAlgebra, and I got segfaults. So I went back to my old code, separating the real and imaginary parts and using the real lu routines.
> 
> Could you post some sample code that triggers this? I probably already have a good test case but it doesn't do any harm to make sure your specific example will work with the fixed code.

I was in a hurry and didn't keep a copy. I'll try to reproduce it again...

> > What still worries me somewhat is the $after_cb parameter of the tensor sub in Photonic::Utils. I haven't understood it but I suspect it is wrong and that if it worked in the SHG tests, it is because they are currently in 1D, but would fail in more dimensions.
> 
> I added the callback parameter that was intended to behave identically to the code that it was replacing in the other similar `tensor`-like (but with an extra dimension) code. If you tell me some code I have made for this stuff has a bug, I of course believe you! Can you make a test-case that captures the error?

Ok.

**Comment by mohawk2** [comment]
I dug into the PDL:LA issue, and it was indeed `RedoDimsCode`-related. The relevant code was assuming for both PDL:C and native complex that the dims offsets were the same. That was clearly wrong! It's now fixed and released as 0.20. Hopefully both your and your colleague's cases will work right now.

**Comment by wlmb** [comment]
> I dug into the PDL:LA issue, and it was indeed `RedoDimsCode`-related. The relevant code was assuming for both PDL:C and native complex that the dims offsets were the same. That was clearly wrong! It's now fixed and released as 0.20. Hopefully both your and your colleague's cases will work right now.

Great! Thanks! Meanwhile I found an issue with the old lu_backsub. I wrote about it in the perldl lists. Regards, Luis

**Comment by wlmb** [comment]
I uploaded the current version of Photonic to cpan, as 0.016. Thanks!

**Comment by mohawk2** [comment]
> > I dug into the PDL:LA issue, and it was indeed `RedoDimsCode`-related. The relevant code was assuming for both PDL:C and native complex that the dims offsets were the same. That was clearly wrong! It's now fixed and released as 0.20. Hopefully both your and your colleague's cases will work right now.
> 
> Great! Thanks! Meanwhile I found an issue with the old lu_backsub. I wrote about it in the perldl lists.

I saw that, and have replied, fixed the issues, and released PDL 2.049. Thanks!

> I uploaded the current version of Photonic to cpan, as 0.016.

Great!

**Comment by mohawk2** [comment]
> I uploaded the current version of Photonic to cpan, as 0.016. Thanks!

Could you also commit and push the repo changes to make it easier to be sure I'm working off latest version? :-)

**Comment by wlmb** [comment]
> > I uploaded the current version of Photonic to cpan, as 0.016. Thanks!
> 
> Could you also commit and push the repo changes to make it easier to be sure I'm working off latest version? :-)

Done! The change I made was pushing the version number.

**Comment by mohawk2** [comment]
> > > I uploaded the current version of Photonic to cpan, as 0.016. Thanks!
> > 
> > 
> > Could you also commit and push the repo changes to make it easier to be sure I'm working off latest version? :-)
> 
> Done! The change I made was pushing the version number.

Great! It's quite common to also tag commits on release, but if you're not doing that, there's no important reason to start.

**Comment by wlmb** [comment]
> Great! It's quite common to also tag commits on release, but if you're not doing that, there's no important reason to start.

It's not a bad idea. I hadn't done it before, but I'll start now.

**Comment by mohawk2** [comment]
@wlmb Regarding memory-mapped storage of ndarrays of states: I've been reading up on File::Map, and it looks like resizing memory-mapped files is only possible on Linux. How do you feel about the states being pre-allocated as the "correct" size from the start? It would mean fixing all of the dimensions especially the maximum number of states (even if not all are used due to convergence); am I right that these things are all known from the start? And that the maximum number of states would be `nh`?

**Comment by wlmb** [comment]
> @wlmb Regarding memory-mapped storage of ndarrays of states: I've been reading up on File::Map, and it looks like resizing memory-mapped files is only possible on Linux. How do you feel about the states being pre-allocated as the "correct" size from the start? It would mean fixing all of the dimensions especially the maximum number of states (even if not all are used due to convergence); am I right that these things are all known from the start? And that the maximum number of states would be `nh`?

Yes, I think you are right. This would affect the size of the file, but not the RAM used, I guess.

**Pull request merged**
