### PR TITLE
Tweaks 10 plus switch to native complex

### PR DESCRIPTION
**Pull request by mohawk2**

### CODE REVIEW

**Comment by mohawk2** [comment]
The tests with the switch to native-complex now seem to run 10% faster, which is nice!

**Comment by wlmb** [comment]
> The tests with the switch to native-complex now seem to run 10% faster, which is nice!

You made the switch already! Amazing! I was worried that it didn't pass the tests in my system, but after reinstalling LinearAlgebra and FFTW3, they did.

**Comment by mohawk2** [comment]
Great! My thinking on the next steps would be to make states be ndarrays (in memory-mapped files as discussed) in order to maximise vectorisation, then I'd quite like to extract out the various applyOperator type code into utility functions with a view to making those utility functions more generally usable by themselves. What do you think?

**Comment by wlmb** [comment]
> Great! My thinking on the next steps would be to make states be ndarrays (in memory-mapped files as discussed) in order to maximise vectorisation, then I'd quite like to extract out the various applyOperator type code into utility functions with a view to making those utility functions more generally usable by themselves. What do you think?

Sounds good.

**Comment by wlmb** [comment]
Hi Ed, Can you point to an example of where we use the non-pdl-ish indices?
(I'll be out for a week+, so I may be slow to answer.)

**Comment by mohawk2** [comment]
Hope your time out is good! No rush :-)

Zeroth, I noticed that you've uploaded the latest code to CPAN (hurrah!). It doesn't look like the `Changes` got updated to reflect the changes made since 0.16. If you're interested, I'll PR what I believe are suitable updates for that file, with a quick note on the practice I follow for CPAN releases.

For example: https://github.com/wlmb/Photonic/blob/57c19457f24748e2e20a1dba43a48e15eb1a9037/lib/Photonic/Utils.pm#L80-L96

First of all, having looked at other of the `::Utils` functions, I believe that my addition of the `$after_cb` should instead have been just a `$skip` parameter as used elsewhere, since that is the only way it's used. If you agree, I'll make a PR.

Another tiny point: the `$nd` parameter's name (which is obviously similar to `$ndims`) caused me confusion for a while, and I think that if I have understood its real purpose, this ought to be renamed to `$ncoords`. If so, there are other places that would need similar renamings (and I'll be happy to make a PR executing this). Additionally, isn't it also possible for there to be dimensional mismatches between a supplied `$nd` parameter and the `$data`? Either that ought to be checked, or the dimensions of the `$tensor` should just come from the `$data`?

On the substantive indexing point, my feeling is now that the `$slice_prefix` variable reveals that we are ordering the dimensions in that ndarray wrong; and instead the two tensorial dims should be at the start, followed by the Cartesian coordinates. With that, the slice arg would just be eg `($i),($j)`. Alternatively, it may be beneficial to rethink the creation of the linear `unitPairs` that are used in creating the tensor. I don't have clear ideas on this yet, but I suspect that raising the question with you, who actually understands this space, will be useful!

After that, I'm not sure yet, but it may also then be possible to drop the `$dims` (and maybe the `$skip`) args entirely. That would need trying out. However, if you're not with me on the previous point, then that ought to be clarified first :-)

**Pull request merged**
