### PR TITLE
Tweaks 5

### PR DESCRIPTION
**Pull request by mohawk2**
These are various further changes towards adopting native complex data.

An important one is that in the very near future, the released PDL will make comparing (`<`, `max`, etc) PDL::Complex numbers a fatal error. The only change *needed* for Photonic to continue working is the "use right agree function" commit, which switches one `agree` to a `Cagree`.

The other big change here is to switch from `lu_backsub` to using LAPACK. This allows use of PDL::Complex objects rather than having to break them into real and imaginary and recombine. LAPACK already works equally with native complex so that makes things easier, and it will also perform a bit quicker both by avoiding the split/recombine, and because `lu_backsub` is in Perl and not C.

There are some changes I'm not yet including here because they depend on PDL changes that aren't released yet (like being able to assign a simple real into a sliced PDL::Complex and not have it affect both real and imaginary, which was always a known PDL::Complex bug), that will either be a later version of this PR, or a separate PR.

By the way, in `wave_operator`, it's still using a `::Real` routine for the linear solve, because I can't yet figure out what the [ [R -I] [I R] ] solved against [ Identity; zeroes ] is. It's obviously connected to Green's functions in some fashion, so I need to actually understand those!

### CODE REVIEW

**Comment by wlmb** [comment]
Hi!
_By the way, in wave_operator, it's still using a ::Real routine for the linear solve, because I can't yet figure out what the [ [R -I] [I R] ] solved against [ Identity; zeroes ] is. It's obviously connected to Green's functions in some fashion, so I need to actually understand those!_

Calling the Green's function G and the wave operator W, their relation is G x W = I, where I is the identity. Writing G=G'+iG'' and W=W'+iW'', this reads (G'+iG'')x(W'+iW'')=I and separating real and imaginiary parts (which won't be required now) they read G'xW'-G''xW''=I, G''xW'+G'xW''=0, two real equations in two real variables, W' and W'', but where each coefficient and each variable is a square matrix. Thus, what wave operator does is arrange the equation above as one real equation where the big block matrix [[G' -G''],[G'' G']] acting on the block column [[W'],[W'']] yields the block column [[I], 0]]. Finally I rearrange W' and W'' into the complex matrix W'+iW''.

**Comment by mohawk2** [comment]
Thanks! That ought to mean it's rearrangeable into a single complex solution-solving, which I was sure was possible.

**Comment by wlmb** [comment]
Yes. That will make its purpose much clearer.

**Comment by wlmb** [comment]
The equation should be greenOperator x waveOperator=complex identity matrix, to be solved for waveOperator.

**Comment by mohawk2** [comment]
I also want to rearrange `tensor` a bit more. It appears to be turning the linear set of inputs into a symmetric matrix. It seems none of the `examples` or test cases give it a value of `$nd` more than 2. I wanted to expand it to 3 (or even better 4), so that I can be sure I get the symmetric matrix right other than by coincidence. Can you steer me on how? It appears the geometry needs to match up with the primitive (particularly its norm, which is where it's blowing up when I extend the Geometry::FromEpsilon from 2 elements to 3), so just a quick pointer on what else to change to 3 (or 4) elements will be extremely helpful! I anticipate that the number of elements will actually expand with the size of the triangular matrix, but clearly I can't easily tell :-)

**Comment by mohawk2** [comment]
> The equation should be greenOperator x waveOperator=complex identity matrix, to be solved for waveOperator.

That should be very easy!

**Comment by mohawk2** [comment]
Another opinion sought! I was looking at PDL::Complex and its tests yesterday, and saw your initials in there from 2013 or so, before I was even associated with the project. I've changed PDL::Complex's comparisons (other than equality) into a fatal error (not yet released), hence the change mentioned here, and would like your take on whether that's a bad idea or not.

**Comment by wlmb** [comment]
> Another opinion sought! I was looking at PDL::Complex and its tests yesterday, and saw your initials in there from 2013 or so, before I was even associated with the project. I've changed PDL::Complex's comparisons (other than equality) into a fatal error (not yet released), hence the change mentioned here, and would like your take on whether that's a bad idea or not.

I don't remember what I did in 2013 :) but I think that comparing for anything but equality (or near equaligy) ought to be wrong and produce an error.

**Comment by mohawk2** [comment]
> I don't remember what I did in 2013 :) but I think that comparing for anything but equality (or near equaligy) ought to be wrong and produce an error.

That's very reassuring, thank you! Regarding equality, the native-complex stuff needed to be able to do exact equality for "bad values" purposes. In the same spirit as the guidance in GNU Scientific Library, which tells writers of GSL functions not to assume what epsilon users may want and just to return the actual differences, if users of PDL complex numbers want near-equality, this will force them to decide (probably using `abs($x) <= $epsilon`), rather than the writers of PDL guessing and getting it mathematically wrong.

**Comment by wlmb** [comment]
> I also want to rearrange `tensor` a bit more. It appears to be turning the linear set of inputs into a symmetric matrix. It seems none of the `examples` or test cases give it a value of `$nd` more than 2. I wanted to expand it to 3 (or even better 4), so that I can be sure I get the symmetric matrix right other than by coincidence. Can you steer me on how? It appears the geometry needs to match up with the primitive (particularly its norm, which is where it's blowing up when I extend the Geometry::FromEpsilon from 2 elements to 3), so just a quick pointer on what else to change to 3 (or 4) elements will be extremely helpful! I anticipate that the number of elements will actually expand with the size of the triangular matrix, but clearly I can't easily tell :-)

i don't know what would go wrong for nd=3 or 4. nd=4 is physically meaningless, but I have tested the package (very long time ago) with nd=4 and it worked. I can guess (blindly), that problems might arise from using the resulting Geometry::FromEpsilon in the NR2 and R2 modules, for which the _value_ of the characteriztic function B is important. The S and NP modules on the other hand use the shape of the characteriztic function, but not its value.  It's a mess, I know. Maybe I should explain a little bit more about the history of the package. But first, is this guess relevant to the problem?

**Comment by wlmb** [comment]
I pulled your changes and after recompiling PDL::LinearAlgebra it seems to work with the new PDL.

**Comment by mohawk2** [comment]
> > I also want to rearrange `tensor` a bit more. It appears to be turning the linear set of inputs into a symmetric matrix. It seems none of the `examples` or test cases give it a value of `$nd` more than 2. I wanted to expand it to 3 (or even better 4), so that I can be sure I get the symmetric matrix right other than by coincidence. Can you steer me on how? It appears the geometry needs to match up with the primitive (particularly its norm, which is where it's blowing up when I extend the Geometry::FromEpsilon from 2 elements to 3), so just a quick pointer on what else to change to 3 (or 4) elements will be extremely helpful! I anticipate that the number of elements will actually expand with the size of the triangular matrix, but clearly I can't easily tell :-)
> 
> i don't know what would go wrong for nd=3 or 4. nd=4 is physically meaningless, but I have tested the package (very long time ago) with nd=4 and it worked. I can guess (blindly), that problems might arise from using the resulting Geometry::FromEpsilon in the NR2 and R2 modules, for which the _value_ of the characteriztic function B is important. The S and NP modules on the other hand use the shape of the characteriztic function, but not its value. It's a mess, I know. Maybe I should explain a little bit more about the history of the package. But first, is this guess relevant to the problem?

I think any thinking about this that requires such explanation would be a sign of error on my part! My aim is specifically ensuring correctness in the `tensor` function, independent of its use by Photonic (you might correctly guess I am thinking about asking you to join me in making a slightly generalised PDL::Physics package out of some of the ::Utils functions, in due course). Therefore, if you can simply give me plausible inputs for say nd=4 to that, and the outline of what the correct output would be, I can run with that.

**Comment by wlmb** [comment]
> I think any thinking about this that requires such explanation would be a sign of error on my part! My aim is specifically ensuring correctness in the `tensor` function, independent of its use by Photonic (you might correctly guess I am thinking about asking you to join me in making a slightly generalised PDL::Physics package out of some of the ::Utils functions, in due course). Therefore, if you can simply give me plausible inputs for say nd=4 to that, and the outline of what the correct output would be, I can run with that.

Ok. I'll build some examples.

**Pull request merged**
