### PR TITLE
Fixups

### PR DESCRIPTION
**Pull request by mohawk2**
This makes a few updates to the project:
- makes the AllH disk-file tests all operate on an individual temporary file, so they can run in parallel
- switches the CI to use GitHub Action
- moves the release tests to `xt` (this cuts down on the test dependencies which makes for a faster install)
- run the release tests on every push/PR
- updates the minimum Perl version to 5.14 because Machine::Epsilon demands that
- changes the copyright year from 1916 to 2016 (let me know if that's not right and I will remove the commit)

Next I intend to add suitable LAPACK functions (I think `[CD]GTTRS`?) to PDL::LinearAlgebra and PR a change for this project to use that, so you can stop packaging the two LINPACK functions and needing to manage the Fortran stuff here entirely.

Thoughts welcome!

### CODE REVIEW

**Comment by wlmb** [comment]
Many thanks @mohawk2 ! I'll take a look this afternoon.

**Comment by mohawk2** [comment]
@wlmb Most welcome! If you can steer me on whether I'm right about which LAPACK function to aim at that would really help :-D

**Comment by wlmb** [comment]
Thanks again for all the suggestions. Very helpful and very generous on your part. I haven't used the GH actions yet, so your file will help me understand them.
The fortran routines I'm using are the old linpack routines  cgtsl.f  dgtsl for solving tridiagonal complex and real systems of equations. They are not identical to the lapack routines [cd]gtsv, [cd]gtsvx, [cd]gttrs but I guess I could use any of those instead; so [cd]gttrs woud be perfect.

**Comment by mohawk2** [comment]
Thanks! Soon as I've adjusted PDL::LinearAlgebra to my liking, another PR will be on its way :-)

GitHub Actions are fairly straightforward once you have a workable pattern to copy from. The biggest problem PDL faces with them is how terribly slow it is to build the whole of PDL when it's just a dependency of something like this. The long-awaited split will help a great deal with this!

**Comment by mohawk2** [comment]
FYI 0.15 of PDL::LinearAlgebra now has [cd]gtsv, with lightly-modified versions of your tests for the LINPACK equivalents. Am now working on converting Photonic over to using them :-)

**Comment by wlmb** [comment]
Thanks!!

**Pull request merged**
