### PR TITLE
Tweaks 6

### PR DESCRIPTION
**Pull request by mohawk2**
You were right about the wave operator! The function couldn't be clearer now. Still looking forward to thoughts on `tensor` :-)

### CODE REVIEW

**Comment by wlmb** [comment]
> You were right about the wave operator! The function couldn't be clearer now. Still looking forward to thoughts on `tensor` :-)

I made a test for a very simple case in 4D and... it passed! I tested the NR2 routines. I still have to test the others.

**Comment by wlmb** [comment]
I added tests of a trivial 4D system (with translationa symmetry along 3 of the 4 dimensions) and verified the expected result. I tested one NR2 routine (t/epst-nr2.t) starting from a characteristic function B and one S routine (t/epst-s.t) starting from a dielectric function so it seems that the tensor building routine is working correctly in 4D. I will add later a direct test of the tensor routine. I would change its name, as it is not a general tensor making routine. It makes a 2D symmetric tensor from its projections along enough independent directions.

**Comment by mohawk2** [comment]
Sounds great! If you give me the better name and the inputs and outputs I can have a go :-)

**Comment by mohawk2** [comment]
By the way, I was looking at `HProd`, and I was a bit surprised that it's complex-conjugating the first parameter and not the second. Is my understanding of Hermitian inner products wrong?

Also, I am wondering what is the benefit of what is now the `any_complex` logic at least there, in order to make the return value "real", rather than keeping them always complex and just accessing real/imaginary as needed? That will also be more important quite soon when native complex (at least temporarily) makes it much harder to treat them separately?

**Comment by mohawk2** [comment]
On that point, I think my tests for the two Hermitian product functions are a bit useless (albeit still useful for at least running the code to see if they actually blow up) in that their inputs have zero imaginary parts, and also are called currently with both params the same.

**Comment by wlmb** [comment]
> By the way, I was looking at `HProd`, and I was a bit surprised that it's complex-conjugating the first parameter and not the second. Is my understanding of Hermitian inner products wrong?

It is correct to conjugate one of the arguments. The usual convention is to conjugate the first and not the second. It could be the other way, but the user should know which convention is used.
> 
> Also, I am wondering what is the benefit of what is now the `any_complex` logic at least there, in order to make the return value "real", rather than keeping them always complex and just accessing real/imaginary as needed? That will also be more important quite soon when native complex (at least temporarily) makes it much harder to treat them separately?

The original PDL::Complex'es were complicated by the fact that complex values could be represented by a real pdl(2...) . In fact, PDL::FFTW3 demanded those kinds of complex numbers. Thus I tried to make the code compatible with whatever the user used,  a PDL or as a PDL::Complex. This is what PDL::FFTW3 does currently, doesn't it?
As this difficulty is about to dissapear, it might be appropiate now or soon to allow only PDL::Complex or native complex pdl's, dying with an error message on entrance if !$iscomplex, i.e., letting the user take care of those conversions if he needs them. But his might break some existing codes. I'm not sure when would be the best time to demand that the input is complex. Now or when using the native complex types?

**Comment by wlmb** [comment]
> On that point, I think my tests for the two Hermitian product functions are a bit useless (albeit still useful for at least running the code to see if they actually blow up) in that their inputs have zero imaginary parts, and also are called currently with both params the same.

I guess more meaningful tests can be built. I can (later) use your testing code and build upon it. It is good to have at least a skeleton for all tests.

**Comment by mohawk2** [comment]
> > By the way, I was looking at `HProd`, and I was a bit surprised that it's complex-conjugating the first parameter and not the second. Is my understanding of Hermitian inner products wrong?
> 
> It is correct to conjugate one of the arguments. The usual convention is to conjugate the first and not the second. It could be the other way, but the user should know which convention is used.

It seems the MathWorld entry (the first hit on Google) should be updated! (Also the Wikipedia entry could be a lot clearer)

> > Also, I am wondering what is the benefit of what is now the `any_complex` logic at least there, in order to make the return value "real", rather than keeping them always complex and just accessing real/imaginary as needed? That will also be more important quite soon when native complex (at least temporarily) makes it much harder to treat them separately?
> 
> The original PDL::Complex'es were complicated by the fact that complex values could be represented by a real pdl(2...) . In fact, PDL::FFTW3 demanded those kinds of complex numbers. Thus I tried to make the code compatible with whatever the user used, a PDL or as a PDL::Complex. This is what PDL::FFTW3 does currently, doesn't it?

PDL::Complex objects and native complex PDLs are represent their complex numbers exactly the same in memory, as pairs of floating-point numbers (single- or double-precision) adjacent within C arrays. In fact, PDL::Complex objects are really a very thin layer over a simple PDL, with a few overridden methods, so (as is done in a number of places in Photonic) slicing them to access only the real or imaginary parts is possible, transpositions dont' work as you'd expect, and moving the `RorI` dimension back and forth is necessary. Those things won't be necessary (or possible without extra work, in fact) with native complex PDLs, since the code generated by the C compiler does the wrangling of the real+imaginary bits.

This meant the only hard bit of making PDL::LinearAlgebra and PDL::FFTW3 take either was simply that in PDL terms, there is an extra dimension (of length 2), which meant generating two versions of the `pp_def` functions, with some tweaks. The C code underlying those PDL libraries doesn't care at all.

> As this difficulty is about to disappear, it might be appropriate now or soon to allow only PDL::Complex or native complex pdl's, dying with an error message on entrance if !$iscomplex, i.e., letting the user take care of those conversions if he needs them. But his might break some existing codes. I'm not sure when would be the best time to demand that the input is complex. Now or when using the native complex types?

The Photonic code already considers either a native complex ndarray, or a PDL::Complex object, to be "complex" (see `any_complex` - the `!$pdl->type->real` detects native complex). The problem I have as PDL person is that making the two types of ndarray interoperate is very hard, because PDL::Complex object fail to conceal that extra dimension. This means effectively a given piece of code needs to pick one style and stick with it. However, there are idioms of code that tie it more closely to PDL::Complex objects, and I am changing those over here as I find (and understand) them :-)

**Comment by wlmb** [comment]
> PDL::Complex objects and native complex PDLs are represent their complex numbers exactly the same in memory, as pairs of floating-point numbers (single- or double-precision) adjacent within C arrays. In fact, PDL::Complex objects are really a very thin layer over a simple PDL, with a few overridden methods, so (as is done in a number of places in Photonic) slicing them to access only the real or imaginary parts is possible, transpositions dont' work as you'd expect, and moving the `RorI` dimension back and forth is necessary. Those things won't be necessary (or possible without extra work, in fact) with native complex PDLs, since the code generated by the C compiler does the wrangling of the real+imaginary bits.
> 
> This meant the only hard bit of making PDL::LinearAlgebra and PDL::FFTW3 take either was simply that in PDL terms, there is an extra dimension (of length 2), which meant generating two versions of the `pp_def` functions, with some tweaks. The C code underlying those PDL libraries doesn't care at all.
> 
> > As this difficulty is about to disappear, it might be appropriate now or soon to allow only PDL::Complex or native complex pdl's, dying with an error message on entrance if !$iscomplex, i.e., letting the user take care of those conversions if he needs them. But his might break some existing codes. I'm not sure when would be the best time to demand that the input is complex. Now or when using the native complex types?
> 
> The Photonic code already considers either a native complex ndarray, or a PDL::Complex object, to be "complex" (see `any_complex` - the `!$pdl->type->real` detects native complex). The problem I have as PDL person is that making the two types of ndarray interoperate is very hard, because PDL::Complex object fail to conceal that extra dimension. This means effectively a given piece of code needs to pick one style and stick with it. However, there are idioms of code that tie it more closely to PDL::Complex objects, and I am changing those over here as I find (and understand) them :-)

The photonic code is aware of the first dimension of size 2, which has produced some headaches and confusion, as not all pdl operations are or were complex-aware. For example:
pdl> $a=sequence(2,10)->complex
pdl> p $a
[0 +1i  2 +3i  4 +5i  6 +7i  8 +9i  10 +11i  12 +13i  14 +15i  16 +17i  18 +19i] 
pdl> p $a->rotate(1)
[1 +0i  3 +2i  5 +4i  7 +6i  9 +8i  11 +10i  13 +12i  15 +14i  17 +16i  19 +18i] 
so rotate interchanges the real and imaginary part, instead or rotating the list of complex numbers. 
Eventually, I would prefer to use only the native complexes as I guess everything will be much cleaner and understandable, but that is a change that would affect all the modules. Thus, I guess it should be done in an alternate branch, not in master until it is finished and tested. Gratefuly, you have added many tests that I had missed.

**Pull request merged**
